### ISSUE TITLE
Fazer apresentação como construir documentações impressionantes

### ISSUE THREAD

**Issue by gabrielbdornas** [lab-mg/novas-ideias#16]
Para incentivar equipe DCD na criação manutenção de atas e outros.

**Comment by gabrielbdornas** [comment]
Incluir @Andrelamor no convite de reunião presencial dia 03/10/2023 quando e-mail planejamento estiver disponível.

**Comment by Andrelamor** [comment]
> Incluir @Andrelamor no convite de reunião presencial dia 03/10/2023 quando e-mail planejamento estiver disponível.

e se meu email não tiver disponível até lá, não preciso comparecer?

**Comment by gabrielbdornas** [comment]
> > Incluir @Andrelamor no convite de reunião presencial dia 03/10/2023 quando e-mail planejamento estiver disponível.
> 
> e se meu email não tiver disponível até lá, não preciso comparecer?

@lab-mg/dcd, solicitei mudança do horário.
@Andrelamor, acredito que até quinta seu e-mail já foi criado! Caso isso já tenha acontecido, favor me informar.

**Comment by Andrelamor** [comment]
> > > Incluir @Andrelamor no convite de reunião presencial dia 03/10/2023 quando e-mail planejamento estiver disponível.
> > 
> > 
> > e se meu email não tiver disponível até lá, não preciso comparecer?
> 
> @lab-mg/dcd, solicitei mudança do horário. @Andrelamor, acredito que até quinta seu e-mail já foi criado! Caso isso já tenha acontecido, favor me informar.

@gabrielbdornas estou preparado para estar lá amanhã Às 09:30

**Comment by gabrielbdornas** [comment]
Devido ao alto volume de coisas para fazer, prefiro voltar este issue para o backlog.

**Comment by gabrielbdornas** [comment]
Apresentação incluída [aqui](https://github.com/lab-mg/reveal.js/tree/master/presentations/20230926_docs_as_code).
